sudo: true
language: cpp
compiler: gcc
addons: 
  apt: 
    packages: libboost-all-dev

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo pip install codecov
  - ./install_oclint.sh

install: sudo apt-get install -qq g++-5

script: 
  - ./build_normal_debug.sh
  - ./build_normal_release.sh
  - ./build_test.sh
  - ./get_code_cov.sh
  - codecov
  - ./do_oclint.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)